myapp/views.py
from flask import Blueprint, render_template, request, url_for, redirect, session, flash, jsonify
from myapp.database import *
from functools import wraps

import pandas as pd
import matplotlib.pyplot as plt
from myapp import socket

views = Blueprint('views', __name__, static_folder='static', template_folder='templates')


# Login decorator to ensure user is logged in before accessing certain routes
def login_required(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        if "user" not in session:
            return redirect(url_for("views.login"))
        return f(*args, **kwargs)

    return decorated


# Index route, this route redirects to login/register page
@views.route("/", methods=["GET", "POST"])
def index():
    """
    Redirects to the login/register page.

    Returns:
        Response: Flask response object.
    """
    return redirect(url_for("views.login"))


# Register a new user and hash password
@views.route("/register", methods=["GET", "POST"])
def register():
    """
    Handles user registration and password hashing.

    Returns:
        Response: Flask response object.
    """
    if request.method == "POST":
        email = request.form["email"].strip().lower()
        username = request.form["username"].strip().lower()
        password = request.form["password"]

        # Check if the user already exists
        existing_user = User.query.filter_by(username=username).first()
        if existing_user:
            flash("User already exists with that username.")
            return redirect(url_for("views.login"))

        # Create a new user
        new_user = User(username=username, email=email, password=password)
        new_user.set_password(password)
        db.session.add(new_user)
        db.session.commit()

        # Create a new chat list for the newly registered user
        new_chat = Chat(user_id=new_user.id, chat_list=[])
        db.session.add(new_chat)
        db.session.commit()

        flash("Registration successful.")
        return redirect(url_for("views.login"))

    return render_template("auth.html")


@views.route("/login", methods=["GET", "POST"])
def login():
    """
    Handles user login and session creation.

    Returns:
        Response: Flask response object.
    """
    if request.method == "POST":
        email = request.form["email"].strip().lower()
        password = request.form["password"]

        # Query the database for the inputted email address
        user = User.query.filter_by(email=email).first()

        if user and user.check_password(password):
            # Create a new session for the newly logged-in user
            session["user"] = {
                "id": user.id,
                "username": user.username,
                "email": user.email,
            }
            return redirect(url_for("views.chat"))
        else:
            flash("Invalid login credentials. Please try again.")
            return redirect(url_for("views.login"))

    return render_template("auth.html")


@views.route("/new-chat", methods=["POST"])
@login_required
def new_chat():
    """
    Creates a new chat room and adds users to the chat list.

    Returns:
        Response: Flask response object.
    """
    user_id = session["user"]["id"]
    new_chat_email = request.form["email"].strip().lower()

    # If user is trying to add themselves, do nothing
    if new_chat_email == session["user"]["email"]:
        return redirect(url_for("views.chat"))

    # Check if the recipient user exists
    recipient_user = User.query.filter_by(email=new_chat_email).first()
    if not recipient_user:
        return redirect(url_for("views.chat"))

    # Check if the chat already exists
    existing_chat = Chat.query.filter_by(user_id=user_id).first()
    """if not existing_chat:
        existing_chat = Chat(user_id=user_id, chat_list=[])
        db.session.add(existing_chat)
        db.session.commit()"""

    # Check if the new chat is already in the chat list
    if recipient_user.id not in [user_chat["user_id"] for user_chat in existing_chat.chat_list]:
        # Generate a room_id (you may use your logic to generate it)
        room_id = str(int(recipient_user.id) + int(user_id))[-4:]

        # Add the new chat to the chat list of the current user
        updated_chat_list = existing_chat.chat_list + [{"user_id": recipient_user.id, "room_id": room_id}]
        existing_chat.chat_list = updated_chat_list

        # Save the changes to the database
        existing_chat.save_to_db()

        # Create a new chat list for the recipient user if it doesn't exist
        recipient_chat = Chat.query.filter_by(user_id=recipient_user.id).first()
        if not recipient_chat:
            recipient_chat = Chat(user_id=recipient_user.id, chat_list=[])
            db.session.add(recipient_chat)
            db.session.commit()

        # Add the new chat to the chat list of the recipient user
        updated_chat_list = recipient_chat.chat_list + [{"user_id": user_id, "room_id": room_id}]
        recipient_chat.chat_list = updated_chat_list
        recipient_chat.save_to_db()

        # Create a new message entry for the chat room
        new_message = Message(room_id=room_id)
        db.session.add(new_message)
        db.session.commit()

    return redirect(url_for("views.chat"))


@views.route("/chat/", methods=["GET", "POST"])
@login_required
def chat():
    """
    Renders the chat interface and displays chat messages.

    Returns:
        Response: Flask response object.
    """
    # Get the room id in the URL or set to None
    room_id = request.args.get("rid", None)

    # Get the chat list for the user
    current_user_id = session["user"]["id"]
    current_user_chats = Chat.query.filter_by(user_id=current_user_id).first()
    chat_list = current_user_chats.chat_list if current_user_chats else []

    # Initialize context that contains information about the chat room
    data = []

    for chat in chat_list:
        # Query the database to get the username of users in a user's chat list
        username = User.query.get(chat["user_id"]).username
        is_active = room_id == chat["room_id"]

        try:
            # Get the Message object for the chat room
            message = Message.query.filter_by(room_id=chat["room_id"]).first()

            # Get the last ChatMessage object in the Message's messages relationship
            last_message = message.messages[-1]

            # Get the message content of the last ChatMessage object
            last_message_content = last_message.content
        except (AttributeError, IndexError):
            # Set variable to this when no messages have been sent to the room
            last_message_content = "This place is empty. No messages ..."

        data.append({
            "username": username,
            "room_id": chat["room_id"],
            "is_active": is_active,
            "last_message": last_message_content,
        })

    # Get all the message history in a certain room
    messages = Message.query.filter_by(room_id=room_id).first().messages if room_id else []

    return render_template(
        "chat.html",
        user_data=session["user"],
        room_id=room_id,
        data=data,
        messages=messages,
    )


# Custom time filter to be used in the jinja template
@views.app_template_filter("ftime")
def ftime(date):
    dt = datetime.fromtimestamp(int(date))
    time_format = "%I:%M %p"  # Use  %I for 12-hour clock format and %p for AM/PM
    formatted_time = dt.strftime(time_format)

    formatted_time += " | " + dt.strftime("%m/%d")
    return formatted_time


@views.route('/visualize')
def visualize():
    """
    TODO: Utilize pandas and matplotlib to analyze the number of users registered to the app.
    Create a chart of the analysis and convert it to base64 encoding for display in the template.

    Returns:
        Response: Flask response object.
    """
    pass


@views.route('/get_name')
def get_name():
    """
    :return: json object with username
    """
    data = {'name': ''}
    if 'username' in session:
        data = {'name': session['username']}

    return jsonify(data)


@views.route('/get_messages')
def get_messages():
    """
    query the database for messages o in a particular room id
    :return: all messages
    """
    pass


@views.route('/leave')
def leave():
    """
    Emits a 'disconnect' event and redirects to the home page.

    Returns:
        Response: Flask response object.
    """
    socket.emit('disconnect')
    return redirect(url_for('views.home'))

myapp/templates/auth.html
<!DOCTYPE html>
<html lang="en">
<head>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <link rel="stylesheet" href="/static/auth.css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" type="text/css" rel="stylesheet">
</head>
<body>
<div class="row">
    <div class="col-md-6 mx-auto p-0">
        <div class="card">
            {% with messages = get_flashed_messages() %}
            {% if messages %}
                <ul class=flashes>
                {% for message in messages %}
                <li>{{ message }}</li>
                {% endfor %}
                </ul>
            {% endif %}
            {% endwith %}
            <div class="login-box">
                <div class="login-snip"> <input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab">Login</label> <input id="tab-2" type="radio" name="tab" class="sign-up"><label for="tab-2" class="tab">Sign Up</label>
                    <div class="login-space">
                        <div class="login">
                        <form method="POST">

                            <div class="group"> <label for="pass" class="label">Email Address</label> <input id="pass" name="email" type="text" class="input" placeholder="Enter your email address"> </div>
                            <div class="group"> <label for="pass" class="label">Password</label> <input id="pass" name="password" type="password" class="input" data-type="password" placeholder="Enter your password"> </div>
                            <div class="group"> <input id="check" type="checkbox" class="check" checked> <label for="check"><span class="icon"></span> Keep me Signed in</label> </div>
                            <div class="group"> <input type="submit" class="button" value="Sign In"> </div>
                            <div class="hr"></div>
                            <div class="foot"> <a href="#">Forgot Password?</a></div>
                        </form>
                        </div>
                        <div class="sign-up-form">
                        <form method="POST" action="{{ url_for('views.register') }}">
                            <div class="group"> <label for="user" class="label">Username</label> <input id="user" name="username" type="text" class="input" placeholder="Create your Username"> </div>
                            <div class="group"> <label for="pass" class="label">Email Address</label> <input id="pass" name="email" type="text" class="input" placeholder="Enter your email address"> </div>
                            <div class="group"> <label for="pass" class="label">Password</label> <input id="pass" name="password" type="password" class="input" data-type="password" placeholder="Create your password"> </div>
                            <div class="group"> <input type="submit" class="button" value="Sign Up"> </div>
                            <div class="hr"></div>
                            <div class="foot"> <label for="tab-1">Already Member?</label> </div>
                        </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

myapp/templates/base.html
<!-- Still coming a common style for the home and visualize  -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="/static/styles.css">
</head>
<body>

</body>
</html>

myapp/templates/chat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Chat Window</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link rel="stylesheet" href="/static/chat.css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" type="text/css"
    rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js" integrity="sha512-q/dWJ3kcmjBLU4Qc47E4A9kTB4m3wuTY7vkFJDTZKjTs8jhyGQnaUrxa0Ytd0ssMZhbNua9hE+E7Qv1j+DyZwA==" crossorigin="anonymous"></script>
</head>
<body>
  <div class="container">
    <div class="container-header">
      <h3 class=" text-left"> {{ user_data["username"] }}</h3>
      <h3 class=" text-center">iChat</h3>
      <h3 class=" text-right">{{ user_data["email"] }}</h3>
    </div>
    <div class="messaging">
      <div class="inbox_msg">
        <div class="inbox_people">
          <div class="headind_srch">
            <div class="recent_heading">
              <h4>Recent</h4>
            </div>
            <div class="srch_bar">
              <div class="stylish-input-group">
                <input type="text" class="search-bar" placeholder="Search">
                <span class="input-group-addon">
                  <button type="button"> <i class="fa fa-search" aria-hidden="true"></i> </button>
                </span>
              </div>
            </div>
            <div class="new_chat">
              <div id="new_chat_overlay"></div>
              <button id="new_chat_btn"><i class="fa fa-plus"></i> New Chat</button>
              <form method="POST" action="{{ url_for('views.new_chat') }}" id="new_chat_form">
                <label for="email"><strong>Email: </strong></label>
                <input type="email" name="email" placeholder="enter friend's email here...">
                <input type="submit" value="Submit">
              </form>
            </div>
          </div>
          <div class="inbox_chat">
            {% for i in data %}
            <a href="{{ url_for('views.chat',rid=i.room_id) }}">
              <div class="chat_list" id="{{ i.room_id }}">
                <div class="chat_people">
                  <div class="chat_img"> <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"> </div>
                  <div class="chat_ib">
                    <h5>{{ i["username"] }}</h5>
                    <p id="last-message">{{ i["last_message"] }}</p>
                  </div>
                </div>
              </div>
            </a>
            {% endfor %}
          </div>
        </div>
        <div class="mesgs">
          <div class="msg_history">
            {% for j in messages %}
              {% if j.sender_username==user_data["username"] %}
              <div class="outgoing_msg" id="{{ j.timestamp }}">
                <div class="sent_msg">
                  <p>{{ j.content }}</p>
                  <span class="time_date">{{ j.timestamp | ftime }}</span>
                </div>
              </div>
              {% else %}
              <div class="incoming_msg" id="{{ j.timestamp }}">
                <div class="incoming_msg_img"> <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil">
                </div>
                <div class="received_msg">
                  <div class="received_withd_msg">
                    <p>{{ j.content }}</p>
                    <span class="time_date">{{ j.timestamp | ftime }}</span>
                  </div>
                </div>
              </div>
              {% endif %}
            {% endfor %}
          </div>
          <div class="type_msg">
            <div class="input_msg_write">
              <form id="chat_form">
                <input type="text" class="message" placeholder="Type a message" />
                <button class="msg_send_btn" type="submit">
                  <i class="fa fa-paper-plane-o" aria-hidden="true"></i>
                </button>
              </form>
            </div>

          </div>
        </div>
      </div>

      <p class="text-center top_spac"> Design by
        <a target="_blank" href="https://www.linkedin.com/in/sunil-rajput-nattho-singh/">Sunil Rajput</a>
      </p>
    </div>
  </div>
  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

  <script type="text/javascript">

    // THIS FUNCTION SHOULD SCROLL DOWN AUTOMATICALLY
    //let scrollingElement = (document.scrollingElement || document.body)
    let msgH = document.querySelectorAll(".msg_history > div"), CurrentLen;
    let init = () => {
      CurrentLen = msgH.length;
    }
    init();
    let validatePosition = () => {
      if (msgH.length === CurrentLen) {
        msgH[msgH.length - 1].setAttribute("id", "last_message");
        for (var i; i < msgH.length; i++) {
          if (msgH[i].id === "last_message" && msgH[i] !== msgH.length - 1) {
            msgH[i].removeAttribute("id");
            msgH[msgH.length - 1].setAttribute("id", "last_message");
          }
        }
      }
    }
    let scrollDown = () => {
      //scrollingElement.scrollTop = scrollingElement.scrollHeight;
      //$container.animate({scrollTop: $container[0].scrollHeight }, "slow");
      validatePosition();
      location.href = "#last_message";
      init();
    }

    // SOCKET CODE
    var socket = io.connect('http://' + document.domain + ':' + location.port + '/?rid=' + {{ room_id }} );
    //scrollDown()
    socket.on('connect', function () {
      socket.emit('join-chat', {
        rid: '{{ room_id }}'
      })
    })

    socket.on('joined-chat', function (msg) {
      console.log(msg)
    })

    var form = $('#chat_form').on('submit', function (e) {
      e.preventDefault()
      let user_input = $('input.message').val()

      socket.emit('outgoing', {
        timestamp: parseInt(Date.now()/1000),
        sender_username: "{{ user_data['username'] }}",
        sender_id: {{ user_data["id"] }},
        message : user_input,
        rid: '{{ room_id }}'
        } )
    //scrollDown();
    $('div.msg_history').append(`
            <div class="outgoing_msg">
              <div class="sent_msg">
                <p>${user_input}</p>
                <span class="time_date"> ${formatDate(new Date())}</span> </div>
            </div>
          `)
    document.getElementById("last-message").innerHTML = user_input
    $('input.message').val('').focus()
    scrollDown();
        } )

    socket.on('message', function (msg) {
      $('div.msg_history').append(`<div class="incoming_msg">
              <div class="incoming_msg_img"> <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"> </div>
              <div class="received_msg">
                <div class="received_withd_msg">
                  <p>${msg.message}</p>
                  <span class="time_date"> ${formatDate(new Date())}</span></div>
              </div>
            </div>`)
      scrollDown();
      document.getElementById("last-message").innerHTML = msg.message
    })

  </script>
  <script>
    function formatDate(date) {
      // Get the hours, minutes, and seconds from the Date object.
      const hours = date.getHours();
      let formattedHours;

      if (hours > 12) {
          formattedHours = hours - 12;
      } else if(hours === 0) {
          formattedHours = 12;
      } else {
          formattedHours = hours;
      }
      const minutes = date.getMinutes();
      //const seconds = date.getSeconds();

      // Get the month and day from the Date object.
      const month = date.getMonth() + 1;
      const day = date.getDate();

      // Create a string with the desired time format.
      const timeFormat = `${formattedHours}:${minutes} ${(hours >= 12) ? 'PM' : 'AM'} | ${month}/${day}`;

      // Return the time format string.
      return timeFormat;
    }
 </script>

  <script>
    window.onload = function () {
      let newChatBtn = document.querySelector('#new_chat_btn');
      let newChatForm = document.querySelector('#new_chat_form');
      let newChatoverlay = document.querySelector('#new_chat_overlay');
      newChatBtn.onclick = (e) => {
        if (e.target === newChatBtn) {
          newChatForm.style.display = "block";
          newChatoverlay.style.display = 'block';

        }
      }
      newChatoverlay.onclick = (e) => {
        if (e.target === newChatoverlay) {
          newChatForm.style.display = "none";
          newChatoverlay.style.display = 'none';
        }
      }
    }
  </script>
</body>
</html>

myapp/templates/visualize.html
{% extends 'base.html' %}

{% block title %}
    DataViz page
{% endblock %}

{% block content %}
  <div class="container mt-5">
    <h1>Data Visualization</h1>
    <hr>

    <div class="row">
      <div class="col-md-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Messages by Hour</h5>
            <img src="data:image/png;base64,{{ chart }}" class="img-fluid">
            <a href="#" class="btn btn-primary mt-3" download="chart.png">Download Chart</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}